### PR TITLE
Support underscores in hexadecimal literals

### PR DESCRIPTION
**Pull request by A-thanasios**
#31

### CODE REVIEW

**Comment by strager** [comment]
Looks great! As I said in person, I'm worried this might negatively impact performance. I'll merge this when we know this doesn't slow things down.

**Comment by strager** [comment]
Benchmark results on my machine comparing commits 007abcbe4 and 2cb9bb3c5:

```
$ ./bench lex --benchmark_repetitions=10 --benchmark_filter=number  
ninja: Entering directory `build-perf'
[10/10] Linking CXX executable benchmark/quick-lint-js-benchmark-lex
2020-10-02 22:45:00
Running ./quick-lint-js-benchmark-lex.before
Run on (4 X 3500 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x2)
  L1 Instruction 32 KiB (x2)
  L2 Unified 256 KiB (x2)
  L3 Unified 4096 KiB (x1)
Load Average: 1.11, 0.65, 0.51
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
--------------------------------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations       byte      bytes
--------------------------------------------------------------------------------------------------
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.73139ns 129.343M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.73838ns 129.226M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428   7.7342ns 129.296M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.73963ns 129.205M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.74371ns 129.137M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.73164ns 129.339M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.74993ns 129.033M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.73543ns 129.275M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428   7.7291ns 129.381M/s
benchmark_lex/tiny_number               15.5 ns         15.5 ns     81185428  7.73775ns 129.237M/s
benchmark_lex/tiny_number_mean          15.5 ns         15.5 ns           10  7.73712ns 129.247M/s
benchmark_lex/tiny_number_median        15.5 ns         15.5 ns           10  7.73659ns 129.256M/s
benchmark_lex/tiny_number_stddev       0.013 ns        0.013 ns           10   6.2745ps 104.757k/s
benchmark_lex/small_number              15.5 ns         15.5 ns     89029887  3.87929ns 257.779M/s
benchmark_lex/small_number              15.5 ns         15.4 ns     89029887  3.86247ns 258.902M/s
benchmark_lex/small_number              15.5 ns         15.5 ns     89029887  3.86889ns 258.472M/s
benchmark_lex/small_number              15.4 ns         15.4 ns     89029887  3.86243ns 258.904M/s
benchmark_lex/small_number              15.5 ns         15.5 ns     89029887  3.86409ns 258.793M/s
benchmark_lex/small_number              15.6 ns         15.6 ns     89029887  3.89366ns 256.828M/s
benchmark_lex/small_number              15.6 ns         15.6 ns     89029887  3.90028ns 256.392M/s
benchmark_lex/small_number              15.6 ns         15.6 ns     89029887  3.90726ns 255.934M/s
benchmark_lex/small_number              15.6 ns         15.6 ns     89029887  3.90887ns 255.829M/s
benchmark_lex/small_number              15.6 ns         15.6 ns     89029887  3.89291ns 256.877M/s
benchmark_lex/small_number_mean         15.5 ns         15.5 ns           10  3.88401ns 257.471M/s
benchmark_lex/small_number_median       15.5 ns         15.5 ns           10   3.8861ns 257.328M/s
benchmark_lex/small_number_stddev      0.075 ns        0.075 ns           10  18.7765ps 1.24448M/s
2020-10-02 22:45:27
Running ./quick-lint-js-benchmark-lex.after0
Run on (4 X 3500 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x2)
  L1 Instruction 32 KiB (x2)
  L2 Unified 256 KiB (x2)
  L3 Unified 4096 KiB (x1)
Load Average: 1.07, 0.68, 0.53
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
--------------------------------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations       byte      bytes
--------------------------------------------------------------------------------------------------
benchmark_lex/tiny_number               16.9 ns         16.9 ns     80823636  8.44142ns 118.464M/s
benchmark_lex/tiny_number               16.7 ns         16.7 ns     80823636  8.33023ns 120.045M/s
benchmark_lex/tiny_number               16.6 ns         16.6 ns     80823636  8.31336ns 120.288M/s
benchmark_lex/tiny_number               16.6 ns         16.6 ns     80823636  8.28143ns 120.752M/s
benchmark_lex/tiny_number               16.6 ns         16.6 ns     80823636  8.29988ns 120.484M/s
benchmark_lex/tiny_number               16.5 ns         16.5 ns     80823636  8.25073ns 121.201M/s
benchmark_lex/tiny_number               16.5 ns         16.5 ns     80823636  8.27099ns 120.905M/s
benchmark_lex/tiny_number               16.4 ns         16.4 ns     80823636  8.22055ns 121.646M/s
benchmark_lex/tiny_number               16.6 ns         16.6 ns     80823636   8.3086ns 120.357M/s
benchmark_lex/tiny_number               16.6 ns         16.6 ns     80823636  8.27847ns 120.795M/s
benchmark_lex/tiny_number_mean          16.6 ns         16.6 ns           10  8.29957ns 120.494M/s
benchmark_lex/tiny_number_median        16.6 ns         16.6 ns           10  8.29065ns 120.618M/s
benchmark_lex/tiny_number_stddev       0.118 ns        0.118 ns           10  59.2102ps 852.446k/s
benchmark_lex/small_number              18.8 ns         18.8 ns     73378861  4.70237ns 212.659M/s
benchmark_lex/small_number              18.8 ns         18.8 ns     73378861  4.70733ns 212.435M/s
benchmark_lex/small_number              18.8 ns         18.8 ns     73378861  4.71171ns 212.237M/s
benchmark_lex/small_number              18.9 ns         18.9 ns     73378861   4.7141ns  212.13M/s
benchmark_lex/small_number              18.9 ns         18.9 ns     73378861  4.71295ns 212.181M/s
benchmark_lex/small_number              18.9 ns         18.9 ns     73378861  4.72381ns 211.693M/s
benchmark_lex/small_number              18.8 ns         18.8 ns     73378861   4.7004ns 212.748M/s
benchmark_lex/small_number              18.9 ns         18.9 ns     73378861  4.72003ns 211.863M/s
benchmark_lex/small_number              18.8 ns         18.8 ns     73378861  4.70108ns 212.717M/s
benchmark_lex/small_number              18.9 ns         18.9 ns     73378861  4.72225ns 211.763M/s
benchmark_lex/small_number_mean         18.8 ns         18.8 ns           10   4.7116ns 212.243M/s
benchmark_lex/small_number_median       18.8 ns         18.8 ns           10  4.71233ns 212.209M/s
benchmark_lex/small_number_stddev      0.035 ns        0.035 ns           10  8.70198ps 391.972k/s
Comparing before.json to after0.json
Benchmark                                           Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------
benchmark_lex/tiny_number                        +0.0918         +0.0918            15            17            15            17
benchmark_lex/tiny_number                        +0.0765         +0.0765            15            17            15            17
benchmark_lex/tiny_number                        +0.0749         +0.0749            15            17            15            17
benchmark_lex/tiny_number                        +0.0700         +0.0700            15            17            15            17
benchmark_lex/tiny_number                        +0.0718         +0.0718            15            17            15            17
benchmark_lex/tiny_number                        +0.0671         +0.0671            15            17            15            17
benchmark_lex/tiny_number                        +0.0672         +0.0672            16            17            15            17
benchmark_lex/tiny_number                        +0.0627         +0.0627            15            16            15            16
benchmark_lex/tiny_number                        +0.0750         +0.0750            15            17            15            17
benchmark_lex/tiny_number                        +0.0699         +0.0699            15            17            15            17
benchmark_lex/tiny_number_pvalue                  0.0002          0.0002      U Test, Repetitions: 10 vs 10
benchmark_lex/tiny_number_mean                   +0.0727         +0.0727            15            17            15            17
benchmark_lex/tiny_number_median                 +0.0716         +0.0716            15            17            15            17
benchmark_lex/tiny_number_stddev                 +8.4087         +8.4366             0             0             0             0
benchmark_lex/small_number                       +0.2122         +0.2122            16            19            16            19
benchmark_lex/small_number                       +0.2187         +0.2187            15            19            15            19
benchmark_lex/small_number                       +0.2178         +0.2178            15            19            15            19
benchmark_lex/small_number                       +0.2205         +0.2205            15            19            15            19
benchmark_lex/small_number                       +0.2197         +0.2197            15            19            15            19
benchmark_lex/small_number                       +0.2132         +0.2132            16            19            16            19
benchmark_lex/small_number                       +0.2051         +0.2051            16            19            16            19
benchmark_lex/small_number                       +0.2080         +0.2080            16            19            16            19
benchmark_lex/small_number                       +0.2027         +0.2027            16            19            16            19
benchmark_lex/small_number                       +0.2130         +0.2130            16            19            16            19
benchmark_lex/small_number_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
benchmark_lex/small_number_mean                  +0.2131         +0.2131            16            19            16            19
benchmark_lex/small_number_median                +0.2126         +0.2126            16            19            16            19
benchmark_lex/small_number_stddev                -0.5369         -0.5365             0             0             0             0
```

21% regression sounds very bad!

**Comment by A-thanasios** [comment]
What are the chances that the obvious slow down is due to adding handling of underscores in hexadecimals? I find that by using 2 separate functions, one for for parsing hexadecimals and underscores and the other for parsing decimal digits and underscores, each function taking only one parameter `char8* input`, I can get benchmarks that resemble your before and after, albeit with an offset as my system runs slower. 

I can get the "before benchmark" by completely gutting all underscore parsing for just hexadecimals and instead just looking for `is_hex_digit` digits and stopping at the last one; this is identical to the original implementation except it's being handled by a function. I can get the "after benchmark" by adding back the underscore parsing for hexadecimals which I removed for the "before benchmark". Note that I've also compared benchmarks to https://github.com/strager/quick-lint-js/commit/007abcbe43cbcf3aee9248227f66f954db7739f5 and they are statistically identical to the "before benchmark" I described above.

Also, I have an implementation which forwards lambdas to a template as discussed yesterday, and its benchmarks resemble the "after benchmark" I described above.

**Review by strager — APPROVED** [review]
Looks great!

Are you fine if I squash your commits into one commit when I merge?

**Comment by A-thanasios** [comment]
> Looks great!
> 
> May I squash your commits into one commit when I merge?

Sure.

**Comment by strager** [comment]
Landed as commit 2682ebdc1999d4e1a062568087ce7d4bd8f57e27.

**Pull request closed without merging**
